# -----------------------------------------------------------------------------
# Copyright (c) 2023 All rights reserved
# -----------------------------------------------------------------------------

DKNAME     	?= rtl-tools
DKTAG      	?= foss
DOCKERFILE 	?= Dockerfile
RUNNER		?= toto

# This include contains the secret sauce
include ../docker.mk
